export const defaultUsersColumns: Column[] = [
  {
    label: "Verification Status",
    display: true,
    value: "is_verified_user",
    filterOptionsData: "is_verified",
    info: "",
    hasSorting: true,
    hasFilter: true,
    isFetch: false,
    selectedOptions: [],
  },
  {
    label: "Email",
    display: true,
    value: "email",
    info: "",
    hasSorting: true,
    hasFilter: false,
    isFetch: false,
  },
  {
    label: "Gender",
    display: false,
    value: "gender",
    filterOptionsData: "gender",
    info: "",
    hasSorting: true,
    hasFilter: true,
    isFetch: false,
    selectedOptions: [],
  },

  {
    label: "SPE",
    display: false,
    value: "voting_engagement_state",
    filterOptionsData: "states",
    info: "State of Political Engagement",
    hasSorting: true,
    hasFilter: true,
    isFetch: true,
    selectedOptions: [],
  },
  {
    label: "Referral Code",
    display: false,
    value: "referral_code",
    info: "",
    hasSorting: true,
    hasFilter: false,
    isFetch: false,
  },
];

export const defaultAnalyticColumns: Column[] = [
  {
    label: "Gender",
    display: true,
    value: "gender",
    filterOptionsData: "gender",
    info: "",
    hasSorting: false,
    hasFilter: true,
    isFetch: false,
    selectedOptions: [],
  },

  {
    label: "LGA",
    display: true,
    value: "lga",
    filterOptionsData: "lgas",
    info: "Local Government Area",
    hasSorting: true,
    hasFilter: true,
    isFetch: true,
    selectedOptions: [],
  },

  {
    label: "State of Origin",
    display: true,
    value: "state_of_origin",
    filterOptionsData: "states",
    info: "",
    hasSorting: true,
    hasFilter: true,
    isFetch: true,
    selectedOptions: [],
  },
  {
    label: "SPE",
    display: true,
    value: "voting_engagement_state",
    filterOptionsData: "states",
    info: "State of Political Engagement",
    hasSorting: true,
    hasFilter: true,
    isFetch: true,
    selectedOptions: [],
  },

  {
    label: "Member Status",
    display: true,
    value: "member_status",
    filterOptionsData: "memberStatus",
    info: "",
    hasSorting: true,
    hasFilter: true,
    isFetch: true,
    selectedOptions: [],
  },
  {
    label: "Position",
    display: true,
    value: "position",
    filterOptionsData: "positions",
    info: "",
    hasSorting: true,
    hasFilter: true,
    isFetch: true,
    selectedOptions: [],
  },

  {
    label: "Age Range",
    display: true,
    value: "age_range",
    filterOptionsData: "ageRanges",
    info: "",
    hasSorting: true,
    hasFilter: true,
    isFetch: true,
    selectedOptions: [],
  },

  {
    label: "Is Registered",
    display: true,
    value: "is_registered",
    filterOptionsData: "booleanOptions",
    info: "Voter Registration Status",
    hasSorting: true,
    hasFilter: true,
    isFetch: false,
    selectedOptions: [],
  },
  {
    label: "Registration Date",
    display: true,
    value: "registration_date",
    info: "Date of Voter Registration",
    hasSorting: true,
    hasFilter: false,
    isFetch: false,
  },
  {
    label: "Registration Status",
    display: true,
    value: "registration_status",
    filterOptionsData: "registrationStatus",
    info: "Current Registration Status",
    hasSorting: true,
    hasFilter: true,
    isFetch: true,
    selectedOptions: [],
  },
  {
    label: "Likely to Vote",
    display: true,
    value: "likely_to_vote",
    filterOptionsData: "likelihoodScale",
    info: "Voting Likelihood",
    hasSorting: true,
    hasFilter: true,
    isFetch: true,
    selectedOptions: [],
  },
  {
    label: "Internet Access",
    display: true,
    value: "has_internet_access",
    filterOptionsData: "booleanOptions",
    info: "Has Regular Internet Access",
    hasSorting: true,
    hasFilter: true,
    isFetch: false,
    selectedOptions: [],
  },
];

export const defaultResourceColumns: Column[] = [
  {
    label: "Title",
    display: true,
    value: "title",
    info: "",
    hasSorting: true,
    hasFilter: false,
    isFetch: false,
  },
  {
    label: "Sub Title",
    display: true,
    value: "sub_title",
    info: "",
    hasSorting: true,
    hasFilter: false,
    isFetch: false,
  },
  {
    label: "Author",
    display: true,
    value: "author",
    info: "",
    hasSorting: true,
    hasFilter: false,
    isFetch: false,
  },
  {
    label: "Resource Links",
    display: true,
    value: "resource_url",
    info: "",
    hasSorting: true,
    hasFilter: false,
    isFetch: false,
  },
];

export const roleOptions = [
  { id: 1, name: "member", value: "member", unavailable: false },
  { id: 2, name: "admin", value: "admin", unavailable: false },
  // { id: 3, name: "verified", value: "verified", unavailable: false },
];

export const defaultChartData: BarChartData = {
  labels: [],
  datasets: [
    {
      label: "",
      data: [],
      backgroundColor: "#FFA048",
    },
  ],
};


